services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Insitaction\FieldEncryptBundle\EventListener\EncryptionListener:
        tags:
            - { name: doctrine.event_listener, event: getEncryptService }

    Insitaction\FieldEncryptBundle\Service\EncryptService:
        arguments: ['%field_encrypt.encrypt_key%']

    Insitaction\FieldEncryptBundle\Service\Misc\CacheItem: ~
